server:
  port: 8002
#actuator info can get
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
eureka:
  client:
    service-url: {"http://localhost8761/eureka/"}
  instance:
    prefer-ip-address: true
spring:
  application:
    name: movie-consumer
user-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#    listOfServers: localhost:8000,localhost:8001