spring:
  datasource:
#    schema: classpath:schema.sql
#    schema: classpath:data.sql
#    创建表需指定utf-8 防止乱码
    hikari:
      username: root
      password:
      jdbc-url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
