spring:
  datasource:
#    schema: classpath:schema.sql
#    schema: classpath:data.sql
#    创建表需指定utf-8 防止乱码
    username: root
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf8&useSSL=false
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
