server:
  port: 8001
spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: h2
#    schema: classpath:schema.sql
    schema: classpath:data.sql
  application:
    name: user-provider
#eureka  /info
info:
  app:
    name: ${spring.application.name}
#    @有时不能出现在yml
#    name: @project.artifactId@
#    encoding: @project.build.sourceEncoding@
#    java:
#      source: @java.version@
#      target: @java.version@
eureka:
  client:
    service-url: {"http://localhost8761/eureka/"}
  instance:
    #ip register not hostname
    prefer-ip-address: true
    #discovery client data
    metadata-map:
      meta1: test
      meta2: test
      meta3: test
#logging:
#  level: off
#  level:
#    cn.luv2code.sample.userprovider.controller.UserController: INFO