spring:
  datasource:
#    schema: classpath:schema.sql
#    schema: classpath:data.sql
#    创建表需指定utf-8 防止乱码
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf8&useSSL=false
custom:
  datasource:
    names: ds1,ds2
    ds1:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://118.25.49.50:3306/db_cooper1?characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
    ds2:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://118.25.49.50:3306/db_cooper2?characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
